### ISSUE TITLE
ConPLex ckpt link broken

### ISSUE THREAD

**Issue by cnellington** [abhinadduri/panspecies-dti#19]

**Comment by abhinadduri** [comment]
faced this same issue when writing colabscreen:

[https://drive.google.com/file/d/1Mhv30\_q6GIBgN2hab0atLeaK0d3AoNm1/view?usp=sharing](https://drive.google.com/file/d/1Mhv30%5C_q6GIBgN2hab0atLeaK0d3AoNm1/view?usp=sharing)

should be without the backslash

[https://drive.google.com/file/d/1Mhv30_q6GIBgN2hab0atLeaK0d3AoNm1/view?usp=sharing](https://drive.google.com/file/d/1Mhv30%5C_q6GIBgN2hab0atLeaK0d3AoNm1/view?usp=sharing)

**Comment by cnellington** [comment]
Resolved in #20
